import type { Field } from '@/types';

// Field definitions for the query builder
// Each field matches a property on the User type
// displayLabel uses "Category ▸ Name" format to match Mixpanel's UI
export const fields: Field[] = [
  {
    name: 'name',
    label: 'Name',
    displayLabel: 'User ▸ Name',
    category: 'User',
    icon: 'text',
    type: 'string',
    description: 'The full name of the user.',
    operators: [
      { name: '=', label: 'Equals' },
      { name: '!=', label: 'Not equal' },
      { name: 'contains', label: 'Contains' },
      { name: 'notContains', label: 'Does not contain' },
      { name: 'startsWith', label: 'Starts with' },
      { name: 'endsWith', label: 'Ends with' },
      { name: 'isSet', label: 'Is set' },
      { name: 'isNotSet', label: 'Is not set' },
    ],
  },
  {
    name: 'company',
    label: 'Company',
    displayLabel: 'User ▸ Company',
    category: 'User',
    icon: 'text',
    type: 'string',
    description: 'The company name associated with the user.',
    operators: [
      { name: '=', label: 'Equals' },
      { name: '!=', label: 'Not equal' },
      { name: 'contains', label: 'Contains' },
      { name: 'notContains', label: 'Does not contain' },
      { name: 'startsWith', label: 'Starts with' },
      { name: 'endsWith', label: 'Ends with' },
      { name: 'isSet', label: 'Is set' },
      { name: 'isNotSet', label: 'Is not set' },
    ],
  },
  {
    name: 'employees',
    label: 'Employees',
    displayLabel: 'User ▸ # employees',
    category: 'User',
    icon: 'number',
    type: 'number',
    description: 'Number of employees at the user\'s company.',
    operators: [
      { name: '=', label: 'Equals' },
      { name: '!=', label: 'Not equal' },
      { name: '>', label: 'Greater than' },
      { name: '>=', label: 'Greater than or equal to' },
      { name: '<', label: 'Less than' },
      { name: '<=', label: 'Less than or equal to' },
      { name: 'between', label: 'Between' },
      { name: 'notBetween', label: 'Not between' },
      { name: 'isNumeric', label: 'Is numeric' },
      { name: 'isNotNumeric', label: 'Is not numeric' },
    ],
  },
  {
    name: 'created',
    label: 'Created',
    displayLabel: 'User ▸ Created',
    category: 'User',
    icon: 'date',
    type: 'date',
    description: 'The time that the profile was created.',
    operators: [
      { name: 'last', label: 'Last' },
      { name: 'notInTheLast', label: 'Not in the last' },
      { name: 'between', label: 'Between' },
      { name: 'notBetween', label: 'Not between' },
      { name: 'on', label: 'On' },
      { name: 'notOn', label: 'Not on' },
      { name: 'beforeTheLast', label: 'Before the last' },
      { name: '<', label: 'Before' },
      { name: 'since', label: 'Since' },
      { name: 'inTheNext', label: 'In the next' },
      { name: 'isSet', label: 'Is set' },
      { name: 'isNotSet', label: 'Is not set' },
    ],
  },
  {
    name: 'lastSeen',
    label: 'Last Seen',
    displayLabel: 'User ▸ Last Seen',
    category: 'User',
    icon: 'date',
    type: 'date',
    description: 'The last time this user was seen.',
    operators: [
      { name: 'last', label: 'Last' },
      { name: 'notInTheLast', label: 'Not in the last' },
      { name: 'between', label: 'Between' },
      { name: 'notBetween', label: 'Not between' },
      { name: 'on', label: 'On' },
      { name: 'notOn', label: 'Not on' },
      { name: 'beforeTheLast', label: 'Before the last' },
      { name: '<', label: 'Before' },
      { name: 'since', label: 'Since' },
      { name: 'inTheNext', label: 'In the next' },
      { name: 'isSet', label: 'Is set' },
      { name: 'isNotSet', label: 'Is not set' },
    ],
  },
  {
    name: 'age',
    label: 'age',
    displayLabel: 'User ▸ age',
    category: 'User',
    icon: 'number',
    type: 'number',
    description: 'User\'s age.',
    operators: [
      { name: '=', label: 'Equals' },
      { name: '!=', label: 'Not equal' },
      { name: '>', label: 'Greater than' },
      { name: '>=', label: 'Greater than or equal to' },
      { name: '<', label: 'Less than' },
      { name: '<=', label: 'Less than or equal to' },
      { name: 'between', label: 'Between' },
      { name: 'notBetween', label: 'Not between' },
      { name: 'isNumeric', label: 'Is numeric' },
      { name: 'isNotNumeric', label: 'Is not numeric' },
    ],
  },
  {
    name: 'firstSeen',
    label: 'First Seen',
    displayLabel: 'First Seen',
    category: 'Computed',
    icon: 'computed',
    type: 'date',
    description: 'First Seen is a datetime profile property that captures the timestamp of the very first event for this user/group. This can be used to filter/segment reports by users who were "new" in a particular timeframe.',
    operators: [
      { name: 'last', label: 'Last' },
      { name: 'notInTheLast', label: 'Not in the last' },
      { name: 'between', label: 'Between' },
      { name: 'notBetween', label: 'Not between' },
      { name: 'on', label: 'On' },
      { name: 'notOn', label: 'Not on' },
      { name: 'beforeTheLast', label: 'Before the last' },
      { name: '<', label: 'Before' },
      { name: 'since', label: 'Since' },
      { name: 'inTheNext', label: 'In the next' },
      { name: 'isSet', label: 'Is set' },
      { name: 'isNotSet', label: 'Is not set' },
    ],
  },
];
